<?php
// phpcs:disable WordPress.NamingConventions.PrefixAllGlobals

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
);
